### ISSUE TITLE
Poor implementation

### ISSUE THREAD

**Issue by AlphaBeth** [hieuminhvuu/Lab6#7]
https://github.com/hieuminhvuu/Lab6/blob/0358e2a535b36e29a6b8bafa2e04b80a5aa3ba38/Server/src/main/java/Ulties/CollectionManager.java#L115-L120

Mutation of external variable from stream isn't good practice.

This code can be replaced with combination of Stream#map, Comparator#reversed, Stream#collect and Collectors#joining

**Comment by hieuminhvuu** [comment]
public static String print_field_descending_weapon_type() {
        ArrayList<SpaceMarine> arr = new ArrayList<>(listSpaceMarine.values());
        StringBuilder stringBuilder = new StringBuilder();
        arr.stream().sorted((SpaceMarine s1, SpaceMarine s2) -> {
           return (s2.getWeapon().compareTo(s1.getWeapon()));
        }).forEach(p->stringBuilder.append(p.toString()));
        return stringBuilder.toString();
    }

**Comment by AlphaBeth** [comment]
Use collect method and predefined Collectorshttps://github.com/hieuminhvuu/Lab6/blob/master/Server/src/main/java/Ulties/CollectionManager.java#L109
